title: Lab Wiki
description: Internal lab know-how and handbook
remote_theme: just-the-docs/just-the-docs

url: https://aiwasaki686.github.io
baseurl: /lab-wiki

search_enabled: true

plugins:
  - jekyll-remote-theme
